<?php
// Debug-protokol
define('catalog_controler_startup_seo_pro__construct', true);
define('catalog_controler_startup_seo_pro__index', true);
define('catalog_controler_startup_seo_pro__rewrite', true);
define('catalog_controler_startup_seo_url__rewrite', true);
define('catalog_controler_startup_seo_url__rewriteLinkWithPrefixes', false);
define('system_library_seopro__baseRewrite', true);
define('system_library_seopro__getKeywordByQuery', true);
define('catalog_model_catalog_product__getProduct', true);
define('catalog_model_catalog_product__getProducts', true);
define('catalog_model_catalog_product__getProductOptcustomersPrice', false);
define('catalog_model_catalog_product__getTotalProducts', false);
define('catalog_model_catalog_product__getProductQuantities', false);
define('catalog_controller_product_manufacturer__index', false);
define('catalog_controller_product_manufacturer__info', false);
define('catalog_controller_product_product__index', true);
define('catalog_model_catalog_review__getTotalReviews', false);
define('catalog_model_catalog_review__getReviews', false);
define('catalog_controller_mail_order__alert', false);
define('catalog_controller_mail_order__add', false);
define('catalog_controler_common_header__index', false);
define('catalog_controller_common_top__index', false);
define('catalog_model_tool_simpleapimain__getLocationList', false);
define('catalog_controller_extension_payment_cod__confirm', false);
define('system_library_cart__getProducts', false);
define('system_library_cart__update', false);
define('catalog_model_checkout_order__addOrderHistory', false);
define('catalog_controller_checkout_cart__add', false);
define('catalog_controller_checkout_cart__edit', false);
define('catalog_controller_common_cart__index', false);
define('catalog_controller_common_footer__callback', false);
define('catalog_controller_common_footer__car_link__show', false);
define('catalog_controller_common_home__index', false);
define('catalog_controller_common_navigation__index', false);
define('catalog_controler_extension_module_jetimpex_megamenu__index', false);
define('catalog_controller_product_category__index', false);
define('catalog_model_extension_shipping_deliveri__getQuote', false);
define('catalog_controller_account_register__index', false);
define('catalog_controller_search_index__getProductsData', false);
define('catalog_controller_product_search__index', true);
define('system_library_export_import_classes_PHPExcel_shared_ZipArchive__open', false);
define('system_library_export_import_classes_PHPExcel_IOFactory__createReaderForFile', false);
define('catalog_controller_common_footer__index', true);


